### ISSUE TITLE
hey how can I help?

### ISSUE THREAD

**Issue by RoboMantis** [gamecredits-project/gmc-dev#1]
I'm pretty new to github and not sure I like it. I program in python and very VERY early stages of C, have experimented with FORTH, which from what I hear is even faster than C because it has a C wrapper it can take C code and compile it with direct threading and registering , rather than criss cross threading compilation.
 I think Atari was written in FORTH?
And a little assembly, which takes for ever.

I saw the .sh, that is C I suppose.

I could do a little python coding, or some tiny example just for fun, pretty please?

Put me up to bat! I won't let you down.

**Comment by KevinBiomech** [comment]
Hello there! Not sure exactly what we need, but I do have a good idea that we can use ya. Why don't you visit us at forum.gamecredits.net and we'll talk.

**Comment by RoboMantis** [comment]
not a big fan of the forum, is there an irc channel?
